networks:
  elastic_net:
    name: elastic_net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24   

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.license.self_generated.type=trial"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail -u elastic:${ELASTIC_PASSWORD} localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      elastic_net:
        ipv4_address: 192.168.20.2
    ports:
      - 9200

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    ports:
      - 5601
    networks:
      elastic_net:
        ipv4_address: 192.168.20.3
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: c69548d9027afcf4d55146b1d425a9f4c69548d9027afcf4d55146b1d425a9f4
    healthcheck:
      test:
        ["CMD-SHELL", "curl --fail -u kibana_system:${KIBANA_PASSWORD} http://localhost:5601 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  conn-es-data: